channels:
  - nodefaults
  - conda-forge
  
dependencies:
  - python>=3.9
  - pip
  - numpy
  - tqdm
  - scipy
  - h5py
  - hdf5plugin
  - tifffile
  - numba
# only needed for GPU operation:
  - cupy
  - cuda-nvcc