channels:
  - nodefaults
  - conda-forge
  
dependencies:
  - python>=3.9
  - pip
  - numpy
# needed for CPU operation:
  - numba
# needed for GPU operation:
  - cupy
  - cuda-nvcc
# needed for CLI:
  - tqdm
  - scipy
  - h5py
  - hdf5plugin
  - tifffile