blank_issues_enabled: true
contact_links:
  - name: General Questions
    url: https://github.com/danionella/opm_unshear/discussions
    about: For general questions or discussions, please visit our Discussions page.